services:
  ruleit_backend:
    build: ./ruleit_backend
    volumes:
      - ./ruleit_backend:/ruleit_backend
    ports:
      - 8000:8000
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=ruleitadmin
    command: /ruleit_backend/entrypoint.sh
    depends_on:
      - ruleit_db

  ruleit_db:
    image: postgres
    ports:
      - 5432:5432
    # volumes: 
    #   - pgdata:/var/lib/postgresql/data
    #   - pgconf:/etc/postgresql
    #   - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=ruleit_db
      - POSTGRES_USER=rule_admin
      - POSTGRES_PASSWORD=iamrulemaker

  ruleit_frontend:
    build:
      context: ./ruleit_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://ruleit_backend:8000/
    volumes:
      - ./ruleit_frontend:/ruleit_frontend 
      - /ruleit_frontend/node_modules
    depends_on:
      - ruleit_backend
    command: npm start

# volumes:
#   pgdata:
#     driver: local
#   pgconf:
#     driver: local
#   pglog: 
#     driver: local
    